version: '3.5'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    environment:
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LOG_LEVEL=warn
    command: etcd -listen-client-urls http://0.0.0.0:2379 -advertise-client-urls http://etcd:2379
    networks:
      - milvus-network

  minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /data
    networks:
      - milvus-network

  milvus:
    image: milvusdb/milvus:v2.0.0
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_USE_SSL=false
      - DATA_COORD_ADDRESS=milvus-dataCoord:19530
    ports:
      - "19530:19530"
    networks:
      - milvus-network

networks:
  milvus-network:
    driver: bridge
